# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "libdart-gir")
set(libdart-gir_VERSION "0.0.0")
set(required_pkgs
  "glib-2.0"
  "gobject-2.0"
)
set(srcfiles
  "src/dart_gir_core.vala"
  "src/gi_compat.vala"
  "src/gir_visitor.vala"
)
set(vapifiles
  "src/dart.vapi"
  "src/gobject-introspection-1.0.vapi"
)
set(uifiles
)
